### ISSUE TITLE
[BUG]: Documentation missing PowerMax and Openshift latest version

### ISSUE THREAD

**Issue by hoppea2** [dell/karavi-authorization#105]
**Describe the bug**
Some of the documentation is not reflecting PowerMax support. The Getting Started Guide is not showing the right supported versions for OpenShift

**To Reproduce**
Steps to reproduce the behavior: Review documentation

**Additional context**
Documentation should be updated to be more generic and to include the correct supported cloud native infrastructure versions.

**Comment by ioeicicdsvc** [comment]
link: 3337
