### ISSUE TITLE
[FEATURE]: Authorization supports PowerScale

### ISSUE THREAD

**Issue by LJ-Software** [dell/karavi-authorization#106]
**Describe the solution you'd like**
CSM Authorization should support PowerScale systems just as it does for PowerFlex and PowerMax.

**Describe alternatives you've considered**
None

**Additional context**
CSM Authorization will need to support credentials shielding and proxying PowerScale csi driver requests to the array.
CSM Authorization will also need to support PowerScale systems being added on the client side with karavictl and creating database entries on the server side for the added systems.

**Comment by hoppea2** [comment]
Completed
