### ISSUE TITLE
[BUG]: Unit tests fail if config.json file not located in user's .karavi/ home directory

### ISSUE THREAD

**Issue by tdawe** [dell/karavi-authorization#93]
**Describe the bug**
Unit tests are failing with error such as: `Config File "config" Not Found in "[/github/workspace/deploy /github/home/.karavi]"`
See example https://github.com/dell/karavi-authorization/runs/2539764273?check_suite_focus=true

**To Reproduce**

1. Clone repository and don't create a config.json file in the user's home .karavi directory.
2. Running unit tests will fail

**Expected behavior**
Tests should be successful

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**

- OS/Version: [e.g. RHEL 7.6]
- Kubernetes Version [e.g. 1.18]
- Additional Information...

**Additional context**

**Comment by ioeicicdsvc** [comment]
link: 3231
