### ISSUE TITLE
[QUESTION]: Can you add karavictl asset to the releases page

### ISSUE THREAD

**Issue by coulof** [dell/karavi-authorization#98]
### How can the Team help you today?

The main authorization module is usually installed on a stand-alone VM while the `karavictl inject` command needs to be executed from box that has access to the main Kubernetes cluster.
Today, I have to either build or scp the `karavictl` command. It will be nice to have it available from the https://github.com/dell/karavi-authorization/releases page.

Thanks !

**Comment by gallacher** [comment]
Thank you for your question @coulof.  I've created a feature assigned to our next milestone to address this: https://github.com/dell/karavi-authorization/issues/101.
